server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  ssl:
    key-store: classpath:keystore/KeyStore.jks
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: JKS
    key-store-provider: SUN
    key-alias: 1
    trust-store: classpath:keystore/TrustStore.jks
    trust-store-password: ${TRUSTSTORE_PASSWORD}
    trust-store-type: JKS
    trust-store-provider: SUN
    enabled: ${SSL_ENABLED:false}

spring:
  application:
    name: ftp-service

logging:
  level:
    root: INFO
    com.nicholasadamou.ftp.service: ${FTP_SERVICE_LOG_LEVEL:INFO}
    org.springframework.web: INFO

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

ssh:
  client:
    host: ${SSH_HOST}
    username: ${SSH_USERNAME}
    password: ${SSH_PASSWORD}
    destination: ${SSH_DESTINATION_FOLDER}
